services:
  postgres:
    image: postgres:18.3
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql"

    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
        reservations:
          cpus: '4'
          memory: 4096M
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

